# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube Openshift'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      sonar.login=admin
      sonar.password=admin
      sonar.projectKey=angular:angular-example
      # sonar.exclusions=**/*.bin

- task: SonarQubeAnalyze@4

- script: |
    npm install          
  displayName: 'Instalar npm'

- task: Npm@1
  displayName: 'Lint Angular (typeScript)'
  inputs:
    command: custom
    customCommand: run lint --  --format=stylish
    workingDir: src

- script: |
    npm run test
  displayName: 'Unit Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    searchFolder: '$(Build.ArtifactStagingDirectory)/**/*.xml'

- script:
    npm run e2e
  displayName: 'e2e Test'

- script: |
    npm run build  
  displayName: 'Construir Aplicación (Build)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'jar -cvf angularUI.war *'
    workingDirectory: 'dist/'    

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/'
    ArtifactName: 'angular-example'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'