kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "teom"
spec:
  source:
    git:
      uri: "https://github.com/acacrc09/angular-example"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfileteom
